// Code generated by goagen v1.4.0, DO NOT EDIT.
//
// API "adder": Application User Types
//
// Command:
// $ goagen
// --design=github.com/k-kurikuri/goa-sandbox/design
// --out=$(GOPATH)/src/github.com/k-kurikuri/goa-sandbox
// --version=v1.3.1

package client
